gunicorn:
  port: 8888 # 接口端口
  workers: 5 # 定义同时开启的处理请求的进程数量，根据网站流量适当调整
postgresql:
  host: 127.0.0.1
  port: 54321
  database: finance
  username: postgres
  password: password
neo4j:
  host: 127.0.0.1
  port: 7474
  username: neo4j
  password: qbneo4j
