app:
  password: admin@123
  secret_key: qwe123zxc
gunicorn:
  port: 8888 # 接口端口
  workers: 5 # 定义同时开启的处理请求的进程数量，根据网站流量适当调整
postgresql:
  host: 47.98.186.79
  port: 6004
  database: postgres
  schema: finance
  username: postgres
  password: password
neo4j:
  host: 47.98.186.79
  port: 6002
  username: neo4j
  password: qbneo4j

